bottles = ['cola', 
'fanta', 
'sprite', 
'orange', 
'maracuja', 
'tonic', 
'limette', 
'sirup', 
'vodka', 
'rum', 
'whisky', 
'tequila', 
'korn', 
'sternmarke']

bottles_objects = [
    {"name": 'cola', "id": 1, "img": "static/images/bottles/cola.png"},
    {"name": 'fanta', "id": 2, "img": "static/images/bottles/fanta.png"},
    {"name": 'sprite', "id": 3, "img": "static/images/bottles/sprite.png"},
    {"name": 'orange', "id": 4, "img": "static/images/bottles/orange.png"},
    {"name": 'maracuja', "id": 5, "img": "static/images/bottles/maracuja.png"},
    {"name": 'tonic', "id": 6, "img": "static/images/bottles/tonic.png"},
    {"name": 'limette', "id": 7, "img": "static/images/bottles/limette.png"},
    {"name": 'sirup', "id": 8, "img": "static/images/bottles/sirup.png"},
    {"name": 'vodka', "id": 9, "img": "static/images/bottles/vodka.png"},
    {"name": 'rum', "id": 10, "img": "static/images/bottles/rum.png"},
    {"name": 'whisky', "id": 11, "img": "static/images/bottles/whisky.png"},
    {"name": 'tequila', "id": 12, "img": "static/images/bottles/tequila.png"},
    {"name": 'korn', "id": 13, "img": "static/images/bottles/korn.png"},
    {"name": 'sternmarke', "id": 14, "img": "static/images/bottles/sternmarke.png"},
    {"name": 'paloma', "id": 15, "img": "static/images/bottles/paloma.png"}
]    